apiVersion: 1

contactPoints:
  - orgId: 1
    name: smartfarm-alerts
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: ""
          singleEmail: false
